apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-deployment
  labels:
    app: eventbus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eventbus
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
        - name: eventbus
          image: i211182/eventbus:latest
          ports:
            - containerPort: 3003
