# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /21i-1182_post

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .


# Expose port 80
EXPOSE 51182

CMD ["npm", "start"]
